// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartFashion.Api.Data;

#nullable disable

namespace FYP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601160000_AddMessagePostAuthorFields")]
    partial class AddMessagePostAuthorFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("SmartFashion.Api.Models.Message", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<bool>("IsRead").HasColumnType("INTEGER");
                    b.Property<string>("MediaUrl").HasColumnType("TEXT");
                    b.Property<int?>("PostId").HasColumnType("INTEGER");
                    b.Property<string>("PostImageUrl").HasColumnType("TEXT");
                    b.Property<string>("PostAuthorName").HasColumnType("TEXT");
                    b.Property<string>("PostAuthorAvatarUrl").HasColumnType("TEXT");
                    b.Property<string>("PostCaption").HasColumnType("TEXT");
                    b.Property<int>("ReceiverId").HasColumnType("INTEGER");
                    b.Property<int>("SenderId").HasColumnType("INTEGER");
                    b.Property<string>("StoryImageUrl").HasColumnType("TEXT");
                    b.Property<string>("Text").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ReceiverId");
                    b.HasIndex("SenderId", "ReceiverId", "CreatedAt");
                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Message", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.User", "Receiver").WithMany().HasForeignKey("ReceiverId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("SmartFashion.Api.Models.User", "Sender").WithMany().HasForeignKey("SenderId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Receiver"); b.Navigation("Sender");
                });
#pragma warning restore 612, 618
        }
    }
}
