// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartFashion.Api.Data;

#nullable disable

namespace FYP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601140000_AddBlocksAndMessageRequests")]
    partial class AddBlocksAndMessageRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("SmartFashion.Api.Models.Block", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("BlockedId").HasColumnType("INTEGER");
                    b.Property<int>("BlockerId").HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("BlockedId");
                    b.HasIndex("BlockerId", "BlockedId").IsUnique();
                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Comment", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<int>("PostId").HasColumnType("INTEGER");
                    b.Property<string>("Text").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("UserId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("PostId");
                    b.HasIndex("UserId");
                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.EmailVerificationCode", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Code").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("TEXT");
                    b.Property<bool>("IsUsed").HasColumnType("INTEGER");
                    b.Property<int>("UserId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("EmailVerificationCodes");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Follow", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<int>("FollowerId").HasColumnType("INTEGER");
                    b.Property<int>("FollowingId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("FollowingId");
                    b.HasIndex("FollowerId", "FollowingId").IsUnique();
                    b.ToTable("Follows");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Like", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<int>("PostId").HasColumnType("INTEGER");
                    b.Property<int>("UserId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("PostId");
                    b.HasIndex("UserId", "PostId").IsUnique();
                    b.ToTable("Likes");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Message", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<bool>("IsRead").HasColumnType("INTEGER");
                    b.Property<string>("MediaUrl").HasColumnType("TEXT");
                    b.Property<int>("ReceiverId").HasColumnType("INTEGER");
                    b.Property<int>("SenderId").HasColumnType("INTEGER");
                    b.Property<string>("StoryImageUrl").HasColumnType("TEXT");
                    b.Property<string>("Text").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ReceiverId");
                    b.HasIndex("SenderId", "ReceiverId", "CreatedAt");
                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.MessageRequest", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("MediaUrl").HasColumnType("TEXT");
                    b.Property<string>("MessageText").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("ReceiverId").HasColumnType("INTEGER");
                    b.Property<int>("SenderId").HasColumnType("INTEGER");
                    b.Property<string>("Status").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("ReceiverId");
                    b.HasIndex("SenderId", "ReceiverId").IsUnique();
                    b.ToTable("MessageRequests");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Notification", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("ActorId").HasColumnType("INTEGER");
                    b.Property<string>("CommentText").HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<bool>("IsRead").HasColumnType("INTEGER");
                    b.Property<int?>("PostId").HasColumnType("INTEGER");
                    b.Property<string>("Type").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("UserId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("ActorId");
                    b.HasIndex("PostId");
                    b.HasIndex("UserId", "CreatedAt");
                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Post", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Caption").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("ImageUrl").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("UserId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "CreatedAt");
                    b.ToTable("Posts");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.PostTag", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("PostId").HasColumnType("INTEGER");
                    b.Property<int>("TaggedUserId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("TaggedUserId");
                    b.HasIndex("PostId", "TaggedUserId").IsUnique();
                    b.ToTable("PostTags");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Story", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Caption").HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("TEXT");
                    b.Property<string>("ImageUrl").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("UserId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "ExpiresAt");
                    b.ToTable("Stories");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.StoryLike", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<int>("StoryId").HasColumnType("INTEGER");
                    b.Property<int>("UserId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.HasIndex("StoryId", "UserId").IsUnique();
                    b.ToTable("StoryLikes");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.StoryView", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<int>("StoryId").HasColumnType("INTEGER");
                    b.Property<DateTime>("ViewedAt").HasColumnType("TEXT");
                    b.Property<int>("ViewerId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("ViewerId");
                    b.HasIndex("StoryId", "ViewerId").IsUnique();
                    b.ToTable("StoryViews");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.TryOnHistory", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("PersonImageUrl").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Prompt").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("ResultImageUrl").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("SelectedOutfitCategory").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("SelectedOutfitColor").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("SelectedOutfitTitle").IsRequired().HasColumnType("TEXT");
                    b.Property<int>("UserId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "CreatedAt");
                    b.ToTable("TryOnHistories");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.User", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("AvatarUrl").HasColumnType("TEXT");
                    b.Property<string>("Bio").HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("FullName").IsRequired().HasColumnType("TEXT");
                    b.Property<bool>("IsEmailVerified").HasColumnType("INTEGER");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Provider").HasColumnType("TEXT");
                    b.Property<string>("Username").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.UserPushToken", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Token").IsRequired().HasColumnType("TEXT");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("TEXT");
                    b.Property<int>("UserId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("UserId").IsUnique();
                    b.ToTable("UserPushTokens");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Block", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.User", "Blocked").WithMany().HasForeignKey("BlockedId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("SmartFashion.Api.Models.User", "Blocker").WithMany().HasForeignKey("BlockerId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Blocked"); b.Navigation("Blocker");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Comment", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.Post", "Post").WithMany("Comments").HasForeignKey("PostId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("SmartFashion.Api.Models.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Post"); b.Navigation("User");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.EmailVerificationCode", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Follow", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.User", "Follower").WithMany().HasForeignKey("FollowerId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("SmartFashion.Api.Models.User", "Following").WithMany().HasForeignKey("FollowingId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Follower"); b.Navigation("Following");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Like", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.Post", "Post").WithMany("Likes").HasForeignKey("PostId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("SmartFashion.Api.Models.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Post"); b.Navigation("User");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Message", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.User", "Receiver").WithMany().HasForeignKey("ReceiverId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("SmartFashion.Api.Models.User", "Sender").WithMany().HasForeignKey("SenderId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Receiver"); b.Navigation("Sender");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.MessageRequest", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.User", "Receiver").WithMany().HasForeignKey("ReceiverId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("SmartFashion.Api.Models.User", "Sender").WithMany().HasForeignKey("SenderId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Receiver"); b.Navigation("Sender");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Notification", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.User", "Actor").WithMany().HasForeignKey("ActorId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.HasOne("SmartFashion.Api.Models.Post", "Post").WithMany().HasForeignKey("PostId");
                    b.HasOne("SmartFashion.Api.Models.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Actor"); b.Navigation("Post"); b.Navigation("User");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Post", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.PostTag", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.Post", "Post").WithMany().HasForeignKey("PostId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("SmartFashion.Api.Models.User", "TaggedUser").WithMany().HasForeignKey("TaggedUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
                    b.Navigation("Post"); b.Navigation("TaggedUser");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Story", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.StoryLike", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.Story", "Story").WithMany("Likes").HasForeignKey("StoryId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("SmartFashion.Api.Models.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Story"); b.Navigation("User");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.StoryView", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.Story", "Story").WithMany("Views").HasForeignKey("StoryId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("SmartFashion.Api.Models.User", "Viewer").WithMany().HasForeignKey("ViewerId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Story"); b.Navigation("Viewer");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.TryOnHistory", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.UserPushToken", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Post", b =>
                { b.Navigation("Comments"); b.Navigation("Likes"); });

            modelBuilder.Entity("SmartFashion.Api.Models.Story", b =>
                { b.Navigation("Views"); b.Navigation("Likes"); });
#pragma warning restore 612, 618
        }
    }
}
