// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartFashion.Api.Data;

#nullable disable

namespace FYP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601180000_AddStoryPostAuthorFields")]
    partial class AddStoryPostAuthorFields
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.13");

            modelBuilder.Entity("SmartFashion.Api.Models.Story", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Caption").HasColumnType("TEXT");
                    b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("TEXT");
                    b.Property<string>("ImageUrl").IsRequired().HasColumnType("TEXT");
                    b.Property<int?>("PostId").HasColumnType("INTEGER");
                    b.Property<string>("PostAuthorName").HasColumnType("TEXT");
                    b.Property<string>("PostAuthorAvatarUrl").HasColumnType("TEXT");
                    b.Property<string>("PostCaption").HasColumnType("TEXT");
                    b.Property<int>("UserId").HasColumnType("INTEGER");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "ExpiresAt");
                    b.ToTable("Stories");
                });

            modelBuilder.Entity("SmartFashion.Api.Models.Story", b =>
                {
                    b.HasOne("SmartFashion.Api.Models.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
